# Generated by Django 3.1.14 on 2023-06-29 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20230628_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date', '-id']},
        ),
    ]
